const sqlite3 = require('sqlite3').verbose();
const bcrypt = require('bcryptjs');
const path = require('path');

// Ajuste o caminho do banco de dados conforme necessário
// Prisma geralmente cria na raiz ou em prisma/dev.db
const dbPath = path.resolve(__dirname, 'prisma/dev.db');
const db = new sqlite3.Database(dbPath);

const email = 'admin@barber.com';
const passwordPlain = '123456';
const name = 'Admin User';
const role = 'ADMIN';
const cpf = '000.000.000-00';
const phone = '(11) 99999-9999';

const now = new Date().toISOString();

bcrypt.hash(passwordPlain, 10, (err, hash) => {
    if (err) {
        console.error(err);
        return;
    }

    db.serialize(() => {
        // Check if user exists
        db.get("SELECT id FROM User WHERE email = ?", [email], (err, row) => {
            if (err) {
                console.error(err);
                return;
            }

            if (row) {
                console.log('User already exists, updating password...');
                db.run("UPDATE User SET password = ?, role = ?, updatedAt = ? WHERE email = ?", [hash, role, now, email], function (err) {
                    if (err) console.error(err);
                    else console.log('User updated');
                });
            } else {
                console.log('Creating user...');
                // ID is usually CUID/UUID. We can generate a random string or let it fail if ID is required and not auto-generated by DB (Prisma does it in client usually).
                // Wait, Prisma schema says @default(cuid()). SQLite doesn't support CUID natively.
                // We need to generate a CUID-like string.
                const id = 'cm' + Math.random().toString(36).substr(2, 9) + Math.random().toString(36).substr(2, 9);

                db.run(`INSERT INTO User (id, email, name, password, role, cpf, phone, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
                    [id, email, name, hash, role, cpf, phone, now, now],
                    function (err) {
                        if (err) console.error(err);
                        else console.log('User created with ID:', id);
                    }
                );
            }
        });
    });
});
